### ISSUE TITLE
TrashcanCleaner is running more than one batch job in parallel?

### ISSUE THREAD

**Issue by hi-ko** [Alfresco/alfresco-trashcan-cleaner-module#11]
Alfresco Repo 7.1.0.1 CE
alfresco-trashcan-cleaner 2.4.1
configuration:
````
trashcan-cleaner.cron=* */30 * * * ?
trashcan-cleaner.keepPeriod=P90D
trashcan-cleaner.deleteBatchCount=5000
````

When the Scheduler starts the TrashcanCleaner I see more than one worker running in parallel which then produce a race condition (it's the first time the job starts directly after starting Alfresco):

````
Apr 12 08:50:19 alf-test alfresco[1980016]: Server startup in [62,321] milliseconds
Apr 12 09:00:00 alf-test alfresco[1980016]: 2022-04-12 09:00:00,122  INFO  [alfresco.trashcan.TrashcanCleaner] [DefaultScheduler_Worker-3] Running TrashcanCleaner
Apr 12 09:00:30 alf-test alfresco[1980016]:  2022-04-12 09:00:30,115  INFO  [alfresco.trashcan.TrashcanCleaner] [DefaultScheduler_Worker-5] Running TrashcanCleaner
Apr 12 09:02:02 alf-test alfresco[1980016]:  2022-04-12 09:02:02,327  INFO  [alfresco.trashcan.TrashcanCleaner] [DefaultScheduler_Worker-3] Number of nodes to delete: 5000
Apr 12 09:02:18 alf-test alfresco[1980016]:  2022-04-12 09:02:18,098  ERROR [quartz.core.JobRunShell] [DefaultScheduler_Worker-5] Job DEFAULT.trashcanCleanerJobDetail threw an unhandled Exception:
Apr 12 09:02:18 alf-test alfresco[1980016]:  org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: archive://SpacesStore/24b38afd-cf17-4dc4-ac45-cc6706d354a8 (status:Status[id=48295116changeTxnId=cc55e52f-06c0-4fd8-a09e-898c109a7412, dbTxnId=43600895, deleted=true])
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl.getNodePairNotNull(DbNodeServiceImpl.java:187)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl.hasAspect_aroundBody38(DbNodeServiceImpl.java:1015)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl$AjcClosure39.run(DbNodeServiceImpl.java:1)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl.hasAspect(DbNodeServiceImpl.java:1009)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.mem.LockableAspectInterceptor.invoke(LockableAspectInterceptor.java:129)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.hasAspect(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.tenant.MultiTNodeServiceInterceptor.invoke(MultiTNodeServiceInterceptor.java:111)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.hasAspect(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.service.StoreRedirectorProxyFactory$RedirectorInvocationHandler.invoke(StoreRedirectorProxyFactory.java:231)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy47.hasAspect(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.MLPropertyInterceptor.getPivotNodeRef(MLPropertyInterceptor.java:329)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.MLPropertyInterceptor.invoke(MLPropertyInterceptor.java:168)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.NodeRefPropertyMethodInterceptor.invoke(NodeRefPropertyMethodInterceptor.java:205)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.getProperty(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor268.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.getProperty(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.olderThanDaysToKeep(TrashcanCleaner.java:175)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.lambda$getBatchToDelete$2(TrashcanCleaner.java:137)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.getBatchToDelete(TrashcanCleaner.java:139)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.lambda$clean$3(TrashcanCleaner.java:217)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.lambda$clean$4(TrashcanCleaner.java:223)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.security.authentication.AuthenticationUtil.runAsSystem(AuthenticationUtil.java:642)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.clean(TrashcanCleaner.java:213)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleanerJob.executeJob(TrashcanCleanerJob.java:62)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.schedule.ScheduledJobLockExecuter.execute(ScheduledJobLockExecuter.java:94)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.schedule.AbstractScheduledLockedJob.executeInternal(AbstractScheduledLockedJob.java:72)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Apr 12 09:02:18 alf-test alfresco[1980016]: 2022-04-12 09:02:18,105  ERROR [quartz.core.ErrorLogger] [DefaultScheduler_Worker-5] Job (DEFAULT.trashcanCleanerJobDetail threw an exception.
Apr 12 09:02:18 alf-test alfresco[1980016]:  org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: archive://SpacesStore/24b38afd-cf17-4dc4-ac45-cc6706d354a8 (status:Status[id=48295116changeTxnId=cc55e52f-06c0-4fd8-a09e-898c109a7412, dbTxnId=43600895, deleted=true])]
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Apr 12 09:02:18 alf-test alfresco[1980016]: Caused by: org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: archive://SpacesStore/24b38afd-cf17-4dc4-ac45-cc6706d354a8 (status:Status[id=48295116changeTxnId=cc55e52f-06c0-4fd8-a09e-898c109a7412, dbTxnId=43600895, deleted=true])
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl.getNodePairNotNull(DbNodeServiceImpl.java:187)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl.hasAspect_aroundBody38(DbNodeServiceImpl.java:1015)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl$AjcClosure39.run(DbNodeServiceImpl.java:1)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.db.DbNodeServiceImpl.hasAspect(DbNodeServiceImpl.java:1009)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.mem.LockableAspectInterceptor.invoke(LockableAspectInterceptor.java:129)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.hasAspect(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.tenant.MultiTNodeServiceInterceptor.invoke(MultiTNodeServiceInterceptor.java:111)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.hasAspect(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.service.StoreRedirectorProxyFactory$RedirectorInvocationHandler.invoke(StoreRedirectorProxyFactory.java:231)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy47.hasAspect(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.MLPropertyInterceptor.getPivotNodeRef(MLPropertyInterceptor.java:329)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.MLPropertyInterceptor.invoke(MLPropertyInterceptor.java:168)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.node.NodeRefPropertyMethodInterceptor.invoke(NodeRefPropertyMethodInterceptor.java:205)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.getProperty(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at jdk.internal.reflect.GeneratedMethodAccessor268.invoke(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at com.sun.proxy.$Proxy30.getProperty(Unknown Source)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.olderThanDaysToKeep(TrashcanCleaner.java:175)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.lambda$getBatchToDelete$2(TrashcanCleaner.java:137)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.getBatchToDelete(TrashcanCleaner.java:139)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.lambda$clean$3(TrashcanCleaner.java:217)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.lambda$clean$4(TrashcanCleaner.java:223)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.repo.security.authentication.AuthenticationUtil.runAsSystem(AuthenticationUtil.java:642)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleaner.clean(TrashcanCleaner.java:213)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.trashcan.TrashcanCleanerJob.executeJob(TrashcanCleanerJob.java:62)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.schedule.ScheduledJobLockExecuter.execute(ScheduledJobLockExecuter.java:94)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.alfresco.schedule.AbstractScheduledLockedJob.executeInternal(AbstractScheduledLockedJob.java:72)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
Apr 12 09:02:18 alf-test alfresco[1980016]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Apr 12 09:02:18 alf-test alfresco[1980016]:         ... 1 more
Apr 12 09:03:13 alf-test alfresco[1980016]: 2022-04-12 09:03:13,145  INFO  [alfresco.trashcan.TrashcanCleaner] [DefaultScheduler_Worker-3] Number of deleted nodes: 5000
Apr 12 09:03:13 alf-test alfresco[1980016]:  2022-04-12 09:03:13,145  INFO  [alfresco.trashcan.TrashcanCleaner] [DefaultScheduler_Worker-3] TrashcanCleaner finished
Apr 12 09:03:13 alf-test alfresco[1980016]:  2022-04-12 09:03:13,147  ERROR [quartz.core.JobRunShell] [DefaultScheduler_Worker-3] Job DEFAULT.trashcanCleanerJobDetail threw an unhandled Exception:
Apr 12 09:03:13 alf-test alfresco[1980016]:  org.alfresco.repo.lock.LockAcquisitionException: 03120603 Failed to release lock '{http://www.alfresco.org/model/system/1.0}trashcancleanerjob' using token 'b282bae0-a6f2-4c6e-9cf9-a8af7fa29001'.  The lock has expired and been taken by another process.
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.domain.locks.AbstractLockDAOImpl.updateLocks(AbstractLockDAOImpl.java:244)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.domain.locks.AbstractLockDAOImpl.releaseLock(AbstractLockDAOImpl.java:182)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.JobLockServiceImpl$3.execute(JobLockServiceImpl.java:459)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.JobLockServiceImpl$3.execute(JobLockServiceImpl.java:1)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.JobLockServiceImpl.releaseLock(JobLockServiceImpl.java:462)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.schedule.ScheduledJobLockExecuter.releaseLock(ScheduledJobLockExecuter.java:163)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.schedule.ScheduledJobLockExecuter.execute(ScheduledJobLockExecuter.java:118)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.schedule.AbstractScheduledLockedJob.executeInternal(AbstractScheduledLockedJob.java:72)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Apr 12 09:03:13 alf-test alfresco[1980016]: 2022-04-12 09:03:13,147  ERROR [quartz.core.ErrorLogger] [DefaultScheduler_Worker-3] Job (DEFAULT.trashcanCleanerJobDetail threw an exception.
Apr 12 09:03:13 alf-test alfresco[1980016]:  org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.alfresco.repo.lock.LockAcquisitionException: 03120603 Failed to release lock '{http://www.alfresco.org/model/system/1.0}trashcancleanerjob' using token 'b282bae0-a6f2-4c6e-9cf9-a8af7fa29001'.  The lock has expired and been taken by another process.]
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Apr 12 09:03:13 alf-test alfresco[1980016]: Caused by: org.alfresco.repo.lock.LockAcquisitionException: 03120603 Failed to release lock '{http://www.alfresco.org/model/system/1.0}trashcancleanerjob' using token 'b282bae0-a6f2-4c6e-9cf9-a8af7fa29001'.  The lock has expired and been taken by another process.
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.domain.locks.AbstractLockDAOImpl.updateLocks(AbstractLockDAOImpl.java:244)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.domain.locks.AbstractLockDAOImpl.releaseLock(AbstractLockDAOImpl.java:182)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.JobLockServiceImpl$3.execute(JobLockServiceImpl.java:459)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.JobLockServiceImpl$3.execute(JobLockServiceImpl.java:1)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.repo.lock.JobLockServiceImpl.releaseLock(JobLockServiceImpl.java:462)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.schedule.ScheduledJobLockExecuter.releaseLock(ScheduledJobLockExecuter.java:163)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.schedule.ScheduledJobLockExecuter.execute(ScheduledJobLockExecuter.java:118)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.alfresco.schedule.AbstractScheduledLockedJob.executeInternal(AbstractScheduledLockedJob.java:72)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
Apr 12 09:03:13 alf-test alfresco[1980016]:         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Apr 12 09:03:13 alf-test alfresco[1980016]:         ... 1 more
````

**Comment by hi-ko** [comment]
the issue is caused by the cron expression. In my case I just replaced the minute element in the default cron expression which still caused the job to theoretical run every second. Second needs to be set fixed. Better real world example 
````
# run between 22:00 and 6:00 every 10 minutes
trashcan-cleaner.cron=0 */10 22-23/1,0-6/1 * * ?
````
